In [1]:
import numpy as np, pandas as pd

In [21]:
# DataFrame as Dictionary of Series(columns)
area = pd.Series({"California": 423967,
                  "Texas": 695662,
                  "New York": 141297,
                  "Florida": 170312,
                  "Illinois": 149995})

pop = pd.Series({"California": 38332521,
                 "Texas": 26448193,
                 "New York": 19651127,
                 "Florida": 19552860,
                 "Illinois": 12882135,})

data = pd.DataFrame({"area": area, "pop": pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [23]:
# Dictionary Style Indexing / DataFrame column name property
print(data["area"], "\n")
print(data.area, "\n") # may or may not work
print(data["area"] is data.area)
print(data["pop"] is data.pop)

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64 

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64 

True
False


In [27]:
# 객체 밴경 (새로운 열 추가)
data["density"] = data["pop"] / data["area"]
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [34]:
# DataFrame as 2D array
print(data.values, "\n") # 데이터 배열 확인

[[4.23967000e+05 3.83325210e+07 9.04139261e+01]
 [6.95662000e+05 2.64481930e+07 3.80187404e+01]
 [1.41297000e+05 1.96511270e+07 1.39076746e+02]
 [1.70312000e+05 1.95528600e+07 1.14806121e+02]
 [1.49995000e+05 1.28821350e+07 8.58837628e+01]] 



In [37]:
# DataFrame 행과 열 교환 (Transpose): .transpose()
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [44]:
# 배열(.values) 단일 인덱스 -> 행 접근
print(data.values[0], "\n")
# DataFrame 단일 인덱스 -> 열 접근
print(data["area"], "\n")

[4.23967000e+05 3.83325210e+07 9.04139261e+01] 

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64 



In [55]:
# loc, iloc, ix

# 암묵적 인덱스 (iloc, end index exclusive)
print(data.iloc[:3, :2]) # iloc[row, col]

# 명시적 인덱스 (loc, end index inclusive)
print(data.loc[:"New York", :"pop"]) # loc[row, col]

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127


In [61]:
# loc w/ 마스킹, 팬시 인덱싱
data.loc[data.density > 100, ["pop", "density"]]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [63]:
# 값 설정/변경
data.iloc[0,2] = 90 # row - 1st, col - 3rd (California density)
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [67]:
# 추가적인 인덱싱
# Indexing - col, Slicing - row
print(data["Florida": "Illinois"])
print(data[1:3]) # 암묵적 인덱스, 3 미포함
print(data[data.density > 100]) # 부울 마스킹

            area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763
            area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746
            area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121
